#!/bin/bash

# Remove auxiliary files generated by LaTeX
rm -f *.aux *.log *.out *.toc *.gz *.bbl *.blg *.synctex.gz *fdb_latexmk *.fls

# Remove generated PDF files
rm -f *.pdf

# Remove temporary files
rm -f *~

echo "Cleanup complete!"
