#!/bin/bash

# Remove auxiliary files generated by LaTeX
find . -type f -name "*.aux" -delete
find . -type f -name "*.log" -delete
find . -type f -name "*.out" -delete
find . -type f -name "*.toc" -delete
find . -type f -name "*.gz" -delete
find . -type f -name "*.bbl" -delete
find . -type f -name "*.blg" -delete
find . -type f -name "*.synctex.gz" -delete
find . -type f -name "*fdb_latexmk" -delete
find . -type f -name "*.fls" -delete

# Remove generated PDF files
find . -type f -name "*.pdf" -delete

# Remove temporary files
find . -type f -name "*~" -delete

echo "Cleanup complete!"
